// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dipdkthavyloydxkakhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpcGRrdGhhdnlsb3lkeGtha2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NDg5NzksImV4cCI6MjA2NjEyNDk3OX0.5g3btmJEgGZ3HVXU0dLlwVmyYMQm2Si2OCAxzkBuby8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);